### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by gammx** [luisanton-io/recoil-nexus#14]
Using fresh install of recoil-nexus `v0.3.10`

![Screenshot_20211221_024156](https://user-images.githubusercontent.com/50937087/146908196-c22fc87f-cb1b-4a34-9e8f-e56a424ac2a9.png)

**Comment by luisanton-io** [comment]
Hi there looks weird, which version of Recoil? Is your project js/ts?
Any info to reproduce is helpful 
L

**Comment by gammx** [comment]
I'm using Typescript with Recoil `v0.5.2` and this is what I have done:

- Install with `npm i recoil-nexus`
- Add RecoilNexus under RecoilRoot
```html
...
<RecoilRoot>
    <RecoilNexus />
    ...
```
- Use setRecoil
```ts
import { setRecoil } from 'recoil-nexus'
//...
setRecoil(currentAtom, currentValue)
```

and after that I'm getting the SyntaxError

**Comment by gammx** [comment]
It works now, steps to solve:
- Change `"module"` property in the recoil-nexus tsconfig.json from `"esnext"` to `"commonjs"`
- Run `npm run build`
