### ISSUE TITLE
Question: setRecoil and Jest - not a function error

### ISSUE THREAD

**Issue by bvelasquez** [luisanton-io/recoil-nexus#17]
Curious how to mock setRecoil in Jest. Currently, I get an error : TypeError: (0 , _recoilNexus.setRecoil) is not a function when trying to mock the function.  I am trying:

```
jest.mock('recoil-nexus', () => {
  return () => ({
    __esModule: true,
    default: jest.fn(),
    setRecoil: jest.fn(),
  });
});
```

However, just receive the error above.

Do you have sample code on mocking setRecoil?

Thank you!

**Comment by luisanton-io** [comment]
Hi there,
just had some time to make up a minimal test example and I hope this could be useful somehow, here is the [CodeSandbox](https://codesandbox.io/s/summer-bush-c1p8f?file=/src/__tests__/index.test.tsx)

I'm not sure to understand why you would need to mock `setRecoil` though, could you please elaborate on that...?
Cheers
