### ISSUE TITLE
Error in Production

### ISSUE THREAD

**Issue by Jordan-Eckowitz** [luisanton-io/recoil-nexus#2]
The package works perfectly when run locally but I get the following error message in production. 

![image](https://user-images.githubusercontent.com/19767538/130393949-08c446bc-fa1b-418e-aced-2c3a91c7be8a.png)

**Comment by luisanton-io** [comment]
Hi Jordan, which version of Recoil and Nexus are you using? 
Also, did you remember to add `<RecoilNexus />` right under your `<RecoilRoot />`?

All is working fine for me this far with recoil v0.4.0 and recoil-nexus v0.3.0 so it would be great if you could somehow help me reproduce the issue.

Thanks!

**Comment by Jordan-Eckowitz** [comment]
yeah good call - my `recoil` package was `v0.3.1` - after updating to `v0.4.0` its working. Thanks for the help.
