### ISSUE TITLE
nexus.get is not a function

### ISSUE THREAD

**Issue by shmshrbali** [luisanton-io/recoil-nexus#20]
Hello, I am planning to use this library for better app structure, when I initially set it up, it was working perfectly, but once I refreshed the application it completely stopped working with the following issue. Let me know what details you need to know.

![image](https://user-images.githubusercontent.com/2536415/166159168-0de2c210-6da7-4903-b96c-09d17e36b2e9.png)

**Comment by shmshrbali** [comment]
Mine is a React App unlike the similar resolved issue, which is for Gatsby.

**Comment by luisanton-io** [comment]
Possibly you are calling getRecoil before your component with RecoilRoot and Recoil Nexus has rendered the first time.

Check your module imports and if this doesn’t help please share the relevant code involved

**Comment by shmshrbali** [comment]
Okay, I tested some of it, and you're totally right, I was creating a variable at the global level. My bad; fixed the scope and it worked out, thank you!
