### ISSUE TITLE
Is there some reason this isn't supported in RecoilJS main project?

### ISSUE THREAD

**Issue by richardanaya** [luisanton-io/recoil-nexus#21]
I'm trying to figure out why such a simple basic functionality isn't in recoil.  Is there some hidden trade off i'm missing?

**Comment by luisanton-io** [comment]
I surely agree this functionality is necessary or at the very least desirable.
No actual issues or drawbacks are experienced this far, but being Recoil itself still experimental it’s correct to be cautious in regards of possible future breaking changes.
