### ISSUE TITLE
can't resolve

### ISSUE THREAD

**Issue by alirezazbr** [luisanton-io/recoil-nexus#23]
I had installed the package, but today I had to remove my node_module and install it again, then full of my project crashed because of recoil-nexus
it says " can't resolve recoil-nexus in project". WHAT SHOULD I DO?!!

**Comment by aurel1997** [comment]
Same problem here
Can't find the `build/` directory in `node_modules/recoil-nexus/`

**Comment by luisanton-io** [comment]
Oh shoot, apologies! That was a bad mistake on mine! I mistakenly published a new version of the package without running the `build` command first. Please download v`0.3.18`!
