### ISSUE TITLE
onSet within Atom effects is broken

### ISSUE THREAD

**Issue by uvera** [luisanton-io/recoil-nexus#24]
After https://github.com/luisanton-io/recoil-nexus/commit/f2aee3cf5fa07a99f228a8dccf7b0f8d885f9760 got merged,
When you try to catch `onSet` (like sync with localStorage with `recoil-persist`), callback passed to `onSet` is not executed.
This is probably because `set` method of `recoil-nexus` is jumping snapshots and not setting state (even though effect's `trigger` was `'set'`).
One workaround I could think of is this:
![image](https://user-images.githubusercontent.com/5598427/177378798-19754cb5-9953-4785-aef1-d41cf475ac6f.png)
Or this:
![image](https://user-images.githubusercontent.com/5598427/177378878-200ed9e4-267c-4fe4-b95d-5dd4a14faf38.png)

**Comment by luisanton-io** [comment]
Thank you for bringing this up! And taking the time to find the root cause. 
This really is rather unfortunate, as both solutions look equally undesirable albeit necessary.

The first one looks "dirty" to me, as I would really be expecting some unpredictable side effects because of the double set.

Instead, checking [the docs](https://recoiljs.org/docs/api-reference/core/useRecoilTransaction/) of the second API, it really looks more unstable than acceptable:

- Atoms with default values that are selectors are also not yet supported.
- Atoms that are read must have a synchronous value. If it is in an error state or an asynchronous pending state, then the transaction will throw an error

Let me play around a little to see how easy is to manually trigger the `onSet`

**Comment by luisanton-io** [comment]
@uvera 
Before getting to work I double checked the bug specifically with Recoil-Persist and it is actually working for me, [here is the usual SandBox](https://codesandbox.io/s/green-firefly-2jkcdg?file=/src/toggleLoading.ts) with the loader example.

As you can see, the effect looks triggered and the localStorage looks set everytime.
Was this not functional in your project?

**Comment by IngusSkaistkalns** [comment]
```tsx
import 'core-js/stable'
import 'regenerator-runtime/runtime'

import React, { useEffect } from 'react'
import { createRoot } from 'react-dom/client'

import { RecoilRoot, atom, AtomEffect } from 'recoil'
import RecoilNexus from 'recoil-nexus'
import { setRecoil } from 'recoil-nexus'

const rootElement = document.getElementById('root')
const root = createRoot(rootElement)

const localStorageEffect =
  (key: string): AtomEffect<string> =>
  ({ setSelf, onSet }) => {
    const savedValue = localStorage.getItem(key)
    if (savedValue != null) {
      setSelf(JSON.parse(savedValue))
    }
    onSet((newValue, _, isReset) => {
      console.log('I never was logged :(', newValue)
      isReset ? localStorage.removeItem(key) : localStorage.setItem(key, JSON.stringify(newValue))
    })
  }

const someAtom = atom<string>({
  key: 'someAtom',
  default: null,
  effects: [localStorageEffect('someAtom')],
})

const App = () => {
  useEffect(() => {
    setRecoil(someAtom, new Date().getTime().toString())
  }, [])
  return <div>TESTING RECOIL</div>
}

root.render(
  <RecoilRoot>
    <RecoilNexus />
    <App />
  </RecoilRoot>
)
```

recoil-nexus 0.3.15 has console log
<img width="379" alt="Screenshot 2022-07-05 at 9 50 58 PM" src="https://user-images.githubusercontent.com/219684/177395943-2f6554d9-edf9-4cf2-91b7-649415b391eb.png">

recoil-nexus 0.3.18 does not have it
<img width="431" alt="Screenshot 2022-07-05 at 9 46 34 PM" src="https://user-images.githubusercontent.com/219684/177396014-1a98c3ec-6d17-4c61-a6d9-8b0bdee45bfb.png">

**Comment by luisanton-io** [comment]
Just released minor v0.4.0, using `transact_UNSTABLE`. I will unpublish patches following v0.3.15 as it was the last "stable" release despite the enqueueing of the `set`.

**Comment by jamiehales** [comment]
The fix here using transact_UNSTABLE unfortunately breaks any atoms utilizing a selector as a default value (which is super common for atoms that populate from an api via a selector). Do you have any suggestions on how we might retain the functionality of the above, without breaking atoms with default selector values?

**Comment by luisanton-io** [comment]
> The fix here using transact_UNSTABLE unfortunately breaks any atoms utilizing a selector as a default value (which is super common for atoms that populate from an api via a selector). Do you have any suggestions on how we might retain the functionality of the above, without breaking atoms with default selector values?

Hi @jamiehales could you open a new issue and link a small sandbox with a reproducible bug? 
To be fair I am not sure to understand from your comment how can a default value be an issue for a subsequent get/set from Nexus. Thank you
