### ISSUE TITLE
First setRecoil fail to update the state when calling setRecoil consecutively

### ISSUE THREAD

**Issue by bcbcbcbcbcl** [luisanton-io/recoil-nexus#25]
I am using "recoil-nexus": "^0.3.18"
First setRecoil is failed to set the state when it is used consecutively. 

Eg: user state is not being set when when calling setRecoil consecutively.
setRecoil(userState, user);
setRecoil(productState, product);

It is working as expected if I add a delay before calling the 2nd setRecoil.

**Comment by luisanton-io** [comment]
I also updated [the usual example](https://github.com/luisanton-io/simple-loader-with-nexus) to see "before"/"after".
[Live on CodeSanbox](https://githubbox.com/luisanton-io/simple-loader-with-nexus) as well if useful.
