### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module 

### ISSUE THREAD

**Issue by ryanchesnut** [luisanton-io/recoil-nexus#5]
I think you need to add 
`type: module`
 to the package json. 
It could be because I'm using Next.js 

Pulled the code into my app directly, everything works great. 

![image](https://user-images.githubusercontent.com/37148876/132793566-f45270e7-ad9a-42d1-a24d-29fb28a8a4bb.png)

**Comment by luisanton-io** [comment]
Fixed on v0.3.3! Needed an extra flag on the tsconfig.json.
Thanks
